version: 1.0.{build}
image: Visual Studio 2017
environment:
  CLI_VERSION: 2.0.0
  MYGET_API_KEY:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  NUGET_API_KEY:
    secure: 4WMsxFFj1s1R+uO8E96HqveIJM77lMWjcWhUnfpXslepnAMlPVigu/SPKnd4aCQn
  
  matrix:
    - Config: Debug
    - Config: Release

build_script:
-  ps: ./build -Configuration $env:Config
test_script:
-  ps: ./test -Configuration $env:Config
artifacts:
  - path: 'Sharp*\**\Sharp*.nupkg'

deploy:
- provider: NuGet
  api_key:
    secure: YllGn/UU5leb3rTBzsuJ/fBlD76dAnZ+V0OGI+AnptcdAUe5i9LqOsaz2VaL0kxo
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
    Config: Release
- provider: NuGet
  server: https://www.myget.org/F/sharpgentools/api/v2/package
  api_key:
    secure: dtTGYQHgEupz5SmTDFkvDW1uEZH7mEM8PD948uzOZY/XCl965mhorbEl2e+6U8pO
  on:
    branch: master
    APPVEYOR_REPO_TAG: false
    Config: Release

matrix:
  fast_finish: true
